Checkpoint 7: Forms
CRClothier/language-blog pull request #7
Opened 2022-07-15 20:20 UTC by CRClothier

- Create a method called current_user in your ApplicationController to make current user data available to all controllers.
- Create forms to perform the following functions:
- Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
- Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).

2022-07-15 20:41 UTC, peterrobert requested changes
Hi @CRClothier, 

Very nice project. I love the way you have paid attention to all the requirements of the project. 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] It will be great to add proper navigation to your project. Example: I don't have a way to create a new comment and also like the posts. I see the controllers are built but I need to be able to navigate to those pages within your app.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 20:41 UTC, peterrobert commented on app/controllers/comments_controller.rb
> +    @comment = @user.comments.new(post: @post, text: params[:text])
- [x] It will be great to use strong parameters for your data. Remember on this[ lesson ](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/Controllers_lesson.md) you learned the need for strong parameters in your controllers. Kindly implement this change.

2022-07-15 20:41 UTC, peterrobert commented on app/controllers/likes_controller.rb
> +    @like.save
- [ ] It is always good practice to check if the resource has been saved eg:
```ruby
  if @like.save
          format.html { redirect_to @post }
        else
          format.html { redirect_to @post }
        end
```
The reason behind this is, Incase something happens or there was an error your app will not break

2022-07-16 17:27 UTC, EricMbouwe approved these changes
Hi @CRClothier, 

Your project is complete! 🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- ⚡ Make requested changes
- ⚡ Routes
## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 17:31 UTC, merged